In [1]:
# <-- Import libraries, custom functions, and load configuration & datasets <--

import yaml
import pandas as pd
import numpy as np
import datetime as dt
import re

# <-- Imports custom preprocessing functions from 'functions.py' <--

from functions import (drop_duplicates,
                       concat_dataframes,
                       remove_all_punctuation,
                       drop_irrelevant_columns,
                       standardize_column_names,
                       filter_by_regex_pattern,
                       standardize_dates
                       )

# <-- Loads YAML configuration to dynamically reference CSV output files. <--

config = None  # <-- Initialize config
try:
    with open("../config.yaml", "r") as file:
        config = yaml.safe_load(file)
except:
    print("Yaml configuration file not found!")
config

job_nyc1 = pd.read_csv(config['input_data']['file1'])
job_nyc2 = pd.read_csv(config['input_data']['file2'])

In [2]:
job_nyc1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5069 entries, 0 to 5068
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Job ID                         5069 non-null   int64
 1   Agency                         5069 non-null   object
 2   Posting Type                   5069 non-null   object
 3   # Of Positions                 5069 non-null   int64
 4   Business Title                 5069 non-null   object
 5   Civil Service Title            5069 non-null   object
 6   Title Classification           5069 non-null   object
 7   Title Code No                  5069 non-null   object
 8   Level                          5069 non-null   object
 9   Job Category                   5069 non-null   object
 10  Full-Time/Part-Time indicator  4990 non-null   object
 11  Career Level                   5069 non-null   object
 12  Salary Range From              5069 non-null   float64
 13  Salary Range To                5069 non-null   float64
 14  Salary Frequency               5069 non-null   object
 15  Work Location                  5069 non-null   object
 16  Division/Work Unit             5069 non-null   object
 17  Job Description                5067 non-null   object
 18  Minimum Qual Requirements      5020 non-null   object
 19  Preferred Skills               3694 non-null   object
 20  Additional Information         2667 non-null   object
 21  To Apply                       4173 non-null   object
 22  Hours/Shift                    1623 non-null   object
 23  Work Location 1                1858 non-null   object
 24  Recruitment Contact            0 non-null      float64
 25  Residency Requirement          5069 non-null   object
 26  Posting Date                   5069 non-null   object
 27  Post Until                     1771 non-null   object
 28  Posting Updated                5069 non-null   object
 29  Process Date                   5069 non-null   object
dtypes: float64(3), int64(2), object(25)
memory usage: 1.2+ MB

In [3]:
job_nyc2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6030 entries, 0 to 6029
Data columns (total 30 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Job ID                         6030 non-null   int64
 1   Agency                         6030 non-null   object
 2   Posting Type                   6030 non-null   object
 3   # Of Positions                 6030 non-null   int64
 4   Business Title                 6030 non-null   object
 5   Civil Service Title            6030 non-null   object
 6   Title Classification           6030 non-null   object
 7   Title Code No                  6030 non-null   object
 8   Level                          6030 non-null   object
 9   Job Category                   6030 non-null   object
 10  Full-Time/Part-Time indicator  6030 non-null   object
 11  Career Level                   6030 non-null   object
 12  Salary Range From              6030 non-null   float64
 13  Salary Range To                6030 non-null   float64
 14  Salary Frequency               6030 non-null   object
 15  Work Location                  6030 non-null   object
 16  Division/Work Unit             6030 non-null   object
 17  Job Description                6030 non-null   object
 18  Minimum Qual Requirements      5963 non-null   object
 19  Preferred Skills               3331 non-null   object
 20  Additional Information         2288 non-null   object
 21  To Apply                       3012 non-null   object
 22  Hours/Shift                    1176 non-null   object
 23  Work Location 1                1459 non-null   object
 24  Recruitment Contact            0 non-null      float64
 25  Residency Requirement          6030 non-null   object
 26  Posting Date                   6030 non-null   object
 27  Post Until                     2183 non-null   object
 28  Posting Updated                6030 non-null   object
 29  Process Date                   6030 non-null   object
dtypes: float64(3), int64(2), object(25)
memory usage: 1.4+ MB

In [4]:
job_nyc1["Preferred Skills"].isnull().sum()

np.int64(1375)

In [5]:
job_nyc2["Preferred Skills"].isnull().sum()

np.int64(2699)

In [6]:
job_nyc1["Preferred Skills"].value_counts(dropna=False)

Preferred Skills
NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        1375
#NAME?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       38
Candidate should possess excellent organizational, verbal, and written skills, with the ability to multi-task various projects. Proficiency in Microsoft Office is preferred.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                18
â¢\tProficient oral and written communication skills to effectively communicate with project staff, engineers/architects, inspectors, consultants, contractors, (foreign and domestic), vendors, City operations staff and external project stakeholders such as regulatory agencies and community representatives.  â¢\tPossession of a motor vehicle driver license valid in the State of New York with no restrictions, which preclude the performance of an Accountable Manager work. This license must be maintained for the duration of employment.  â¢\tHave a detailed understanding of permitting, equipment and materials, codes and standards, shop/field testing.  â¢\tAble to determine adequacy and completeness of field investigation plans and reports to support the development of more complex designs or scope change requests.  â¢\tAbility to assess applicability and appropriateness of field investigation protocols for stated objectives.  â¢\tPossess a working knowledge of current safety and design standards.  â¢\tAble to review, interpret and approve complex contract documents.   â¢\tAble to understand the necessary project resources to effectively identify upcoming needs or existing conflicts.  â¢\tAble to assess consultant/contractor performance based on contract requirements.   â¢\tAble to evaluate project progress regularly in terms of potential impacts to schedule compliance.  â¢\tUnderstand schedule implications of change orders and recovery plans.  â¢\tUnderstand the process to prepare the Communication Management Plan.  â¢\tEmploy effective time management practices.  â¢\tKnowledge of engineering design and construction industry standards and practices as well as environmental engineering operations and processes for water supply and wastewater resource recovery facilities.   â¢\tStrong technical skills, interpersonal, communication, and computer skills with a working knowledge of MS Office software, and Project Scheduling Software.  â¢\tKnowledge of operations and processes for wastewater resource recovery facilities.  â¢\tKnowledge of design and construction industry standards and practices as well as a strong ability to work on a broad multidisciplinary base with various fields and trades as well as the ability to concurrently handle multiple related and non-related tasks.  â¢\tExperience in writing and reviewing contract specifications for major public works projects.      14
â¢\tCandidates must be able to demonstrate critical thinking skills and effective independent data analysis  â¢\tExcellent oral and written communication skills, ability to meet deadlines, and an ability to be flexible in assignment of work responsibilities  â¢\tUnderstanding of water and heavy civil infrastructure design practices and standards  â¢\tUnderstanding of project management principals, specifically the procedures used by DEP  â¢\tThis position requires operation of a motor vehicle to perform site visits, equipment testing, inspections, and to attend meetings with project stakeholders  â¢\tKnowledge of Microsoft Office Suite products (Word, Excel, etc.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       14
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ...
1.\tAbility to work with a team on specialized tasks. 2.\tProficiency in Microsoft Office Suite. 3.\tAvailable to work weekends and evenings as needed. 4.\tValid New York State driver license. 5.\tBilingual.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               1
The candidate must have a valid Professional Engineerâs license and a valid driversâ license.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1

In [7]:
display(pd.DataFrame({
    "non_nulls": job_nyc1.count(),
    "nulls": job_nyc1.isnull().sum(),
    "total": len(job_nyc1)
}))

                               non_nulls  nulls  total
Job ID                              5069      0   5069
Agency                              5069      0   5069
Posting Type                        5069      0   5069
# Of Positions                      5069      0   5069
Business Title                      5069      0   5069
Civil Service Title                 5069      0   5069
Title Classification                5069      0   5069
Title Code No                       5069      0   5069
Level                               5069      0   5069
Job Category                        5069      0   5069
Full-Time/Part-Time indicator       4990     79   5069
Career Level                        5069      0   5069
Salary Range From                   5069      0   5069
Salary Range To                     5069      0   5069
Salary Frequency                    5069      0   5069
Work Location                       5069      0   5069
Division/Work Unit                  5069      0   5069
Job Description                     5067      2   5069
Minimum Qual Requirements           5020     49   5069
Preferred Skills                    3694   1375   5069
Additional Information              2667   2402   5069
To Apply                            4173    896   5069
Hours/Shift                         1623   3446   5069
Work Location 1                     1858   3211   5069
Recruitment Contact                    0   5069   5069
Residency Requirement               5069      0   5069
Posting Date                        5069      0   5069
Post Until                          1771   3298   5069
Posting Updated                     5069      0   5069
Process Date                        5069      0   5069

In [8]:
display(pd.DataFrame({
    "non_nulls": job_nyc2.count(),
    "nulls": job_nyc2.isnull().sum(),
    "total": len(job_nyc2)
}))

                               non_nulls  nulls  total
Job ID                              6030      0   6030
Agency                              6030      0   6030
Posting Type                        6030      0   6030
# Of Positions                      6030      0   6030
Business Title                      6030      0   6030
Civil Service Title                 6030      0   6030
Title Classification                6030      0   6030
Title Code No                       6030      0   6030
Level                               6030      0   6030
Job Category                        6030      0   6030
Full-Time/Part-Time indicator       6030      0   6030
Career Level                        6030      0   6030
Salary Range From                   6030      0   6030
Salary Range To                     6030      0   6030
Salary Frequency                    6030      0   6030
Work Location                       6030      0   6030
Division/Work Unit                  6030      0   6030
Job Description                     6030      0   6030
Minimum Qual Requirements           5963     67   6030
Preferred Skills                    3331   2699   6030
Additional Information              2288   3742   6030
To Apply                            3012   3018   6030
Hours/Shift                         1176   4854   6030
Work Location 1                     1459   4571   6030
Recruitment Contact                    0   6030   6030
Residency Requirement               6030      0   6030
Posting Date                        6030      0   6030
Post Until                          2183   3847   6030
Posting Updated                     6030      0   6030
Process Date                        6030      0   6030

In [9]:
df_merged = concat_dataframes(job_nyc1,job_nyc2)

In [10]:
df_merged = standardize_column_names(df_merged)

In [11]:
display(df_merged.columns)

Index(['job_id', 'agency', 'posting_type', '#_of_positions', 'business_title',
       'civil_service_title', 'title_classification', 'title_code_no', 'level',
       'job_category', 'full-time/part-time_indicator', 'career_level',
       'salary_range_from', 'salary_range_to', 'salary_frequency',
       'work_location', 'division/work_unit', 'job_description',
       'minimum_qual_requirements', 'preferred_skills',
       'additional_information', 'to_apply', 'hours/shift', 'work_location_1',
       'recruitment_contact', 'residency_requirement', 'posting_date',
       'post_until', 'posting_updated', 'process_date'],
      dtype='object')

In [12]:
df_merged[['posting_date','post_until','posting_updated','process_date']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11099 entries, 0 to 11098
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   posting_date     11099 non-null  object
 1   post_until       3954 non-null   object
 2   posting_updated  11099 non-null  object
 3   process_date     11099 non-null  object
dtypes: object(4)
memory usage: 347.0+ KB

In [13]:
df_merged = drop_duplicates(df_merged,'job_id')

In [14]:
columns = ['posting_type', 'civil_service_title', 'title_classification', 
'title_code_no', 'full-time/part-time_indicator', 'work_location', 'division/work_unit',
'job_description', 'minimum_qual_requirements', 'additional_information', 'to_apply', 
'hours/shift', 'work_location_1', 'recruitment_contact', 'residency_requirement', 'posting_updated',
'process_date']

df_merged = drop_irrelevant_columns(df_merged, columns)

In [15]:
display(df_merged.columns)

Index(['job_id', 'agency', '#_of_positions', 'business_title', 'level',
       'job_category', 'career_level', 'salary_range_from', 'salary_range_to',
       'salary_frequency', 'preferred_skills', 'posting_date', 'post_until'],
      dtype='object')

In [16]:
display(df_merged.isnull().sum())

job_id                  0
agency                  0
#_of_positions          0
business_title          0
level                   0
job_category            0
career_level            0
salary_range_from       0
salary_range_to         0
salary_frequency        0
preferred_skills     1933
posting_date            0
post_until           3270
dtype: int64

In [17]:
display(pd.DataFrame({
    "non_nulls": df_merged.count(),
    "nulls": df_merged.isnull().sum(),
    "total": len(df_merged)
}))

                   non_nulls  nulls  total
job_id                  5271      0   5271
agency                  5271      0   5271
#_of_positions          5271      0   5271
business_title          5271      0   5271
level                   5271      0   5271
job_category            5271      0   5271
career_level            5271      0   5271
salary_range_from       5271      0   5271
salary_range_to         5271      0   5271
salary_frequency        5271      0   5271
preferred_skills        3338   1933   5271
posting_date            5271      0   5271
post_until              2001   3270   5271

In [18]:
cat_cols = list(df_merged.select_dtypes(include=['object']))
cat_cols

['agency',
 'business_title',
 'level',
 'job_category',
 'career_level',
 'salary_frequency',
 'preferred_skills',
 'posting_date',
 'post_until']

In [19]:
# Clean up categorical columns (type = 'object') except dates
cat_cols = ['agency',
 'business_title',
 'level',
 'job_category',
 'career_level',
 'salary_frequency',
 'preferred_skills']
 
df_merged = remove_all_punctuation(df_merged,cat_cols)

In [20]:
df_merged['preferred_skills']

0                             must have a valid pe license
1         student must currently be enrolled at a colle...
2                                                      NaN
3         a baccalaureate degree from an accredited col...
4        preference will be given to candidates with at...
                               ...
10906                                                  NaN
10957                                                  NaN
10961                                                  NaN
11037                                                  NaN
11047    very strong preference given to candidates dem...
Name: preferred_skills, Length: 5271, dtype: object

In [21]:
df_merged[['preferred_skills','job_category','career_level']]

,preferred_skills,job_category,career_level
0,must have a valid pe license,engineering architecture planning,experienced non
1,student must currently be enrolled at a colle...,engineering architecture planning,student
2,NaN,communications intergovernmental affairs tech...,experienced non
3,a baccalaureate degree from an accredited col...,engineering architecture planning,experienced non
4,preference will be given to candidates with at...,engineering architecture planning,manager
...,...,...,...
10906,NaN,administration human resources,experienced non
10957,NaN,engineering architecture planning public safe...,experienced non
10961,NaN,communications intergovernmental affairs,manager
11037,NaN,communications intergovernmental affairs,manager
11047,very strong preference given to candidates dem...,constituent services community programs engin...,experienced non

In [22]:
df_merged[['posting_date', 'post_until']]

      posting_date post_until
0       06/08/2022        NaN
1       04/02/2024  11-Jun-24
2       02/27/2024  26-Feb-25
3       03/05/2024  29-May-24
4       11/06/2023        NaN
...            ...        ...
10906   10/18/2024        NaN
10957   04/25/2025        NaN
10961   05/29/2025        NaN
11037   05/12/2025        NaN
11047   07/27/2024        NaN

[5271 rows x 2 columns]

In [23]:
date_format_map = {
    'posting_date': '%m/%d/%Y',
    'post_until': '%d-%b-%y'
}
df_merged = standardize_dates(df_merged, date_format_map)

In [24]:
df_merged[['job_id','posting_date','post_until','career_level']].sort_values('posting_date',ascending=False)

      job_id posting_date post_until      career_level
5538  729445   2025-09-16 2025-09-30  experienced non
7619  732378   2025-09-15 2025-10-05            entry
6957  735562   2025-09-15 2026-09-15  experienced non
5366  736118   2025-09-15 2025-10-15  experienced non
8135  724461   2025-09-15 2025-09-30  experienced non
...      ...          ...        ...               ...
2706  487203   2021-09-30        NaT  experienced non
2202  484513   2021-09-22        NaT  experienced non
416   483894   2021-09-17        NaT  experienced non
1173  483469   2021-09-13        NaT  experienced non
1886  469953   2021-07-26        NaT  experienced non

[5271 rows x 4 columns]

In [25]:
df_merged[['posting_date','post_until']].info()

<class 'pandas.core.frame.DataFrame'>
Index: 5271 entries, 0 to 11047
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   posting_date  5271 non-null   datetime64[ns]
 1   post_until    2001 non-null   datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 123.5 KB

In [26]:
df_merged['career_level'].unique()

array(['experienced non ', 'student', 'manager', 'entry ', 'executive'],
      dtype=object)

In [27]:
# for career, group in df_merged.groupby('career_level'):
#     print(f"Career Level: {career}")
#     print(group[['job_id', 'posting_date', 'post_until']])

grouped = df_merged.groupby('career_level')[['job_id','posting_date','post_until']].apply(lambda x: x)
grouped.sort_values(['career_level','job_id'],ascending=True)

                   job_id posting_date post_until
career_level
entry        3015  526438   2022-03-25        NaT
             2214  527780   2022-04-08        NaT
             3569  527788   2022-04-13        NaT
             811   527794   2022-04-13        NaT
             1979  527821   2022-04-13        NaT
...                   ...          ...        ...
student      6066  732764   2025-09-04 2026-09-04
             7691  733340   2025-09-05        NaT
             8263  733480   2025-09-05        NaT
             7861  733492   2025-09-05 2025-09-20
             9256  734392   2025-09-08 2025-09-22

[5271 rows x 3 columns]

In [28]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5271 entries, 0 to 11047
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_id             5271 non-null   int64
 1   agency             5271 non-null   object
 2   #_of_positions     5271 non-null   int64
 3   business_title     5271 non-null   object
 4   level              5271 non-null   object
 5   job_category       5271 non-null   object
 6   career_level       5271 non-null   object
 7   salary_range_from  5271 non-null   float64
 8   salary_range_to    5271 non-null   float64
 9   salary_frequency   5271 non-null   object
 10  preferred_skills   3338 non-null   object
 11  posting_date       5271 non-null   datetime64[ns]
 12  post_until         2001 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(7)
memory usage: 576.5+ KB

In [29]:
display(df_merged['business_title'])

0                                        region supervisor
1        2024 010  warning remote modeling intern valhalla
2                                     intelligence analyst
3                      senior coordinator capital projects
4                                                 director
                               ...
10906                        deputy director of onboarding
10957                             environmental specialist
10961                       deputy communications director
11037                  director for digital communications
11047    greenways project lead  office of livable streets
Name: business_title, Length: 5271, dtype: object

In [30]:
regex_pattern = r"\b(data analyst|data engineer|business analyst|data science|data scientist)\w*\b"
# regex_pattern = r"\b(data analyst)\b|\b(data engineer)\b|\b(business analyst)\b|\b(data science)\b|\b(data scientist)\b"
df_data_analyst = filter_by_regex_pattern(df_merged,'business_title', regex_pattern)

d:\vscode101\first_project\notebooks\functions.py:54: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df[column].str.contains(regex_pattern, flags=re.IGNORECASE, na=False, regex=True)

In [31]:
df_data_analyst.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_id             73 non-null     int64
 1   agency             73 non-null     object
 2   #_of_positions     73 non-null     int64
 3   business_title     73 non-null     object
 4   level              73 non-null     object
 5   job_category       73 non-null     object
 6   career_level       73 non-null     object
 7   salary_range_from  73 non-null     float64
 8   salary_range_to    73 non-null     float64
 9   salary_frequency   73 non-null     object
 10  preferred_skills   40 non-null     object
 11  posting_date       73 non-null     datetime64[ns]
 12  post_until         51 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(7)
memory usage: 7.5+ KB

In [32]:
display(pd.DataFrame({
    "non_nulls": df_data_analyst.count(),
    "nulls": df_data_analyst.isnull().sum(),
    "total": len(df_data_analyst)
}))

                   non_nulls  nulls  total
job_id                    73      0     73
agency                    73      0     73
#_of_positions            73      0     73
business_title            73      0     73
level                     73      0     73
job_category              73      0     73
career_level              73      0     73
salary_range_from         73      0     73
salary_range_to           73      0     73
salary_frequency          73      0     73
preferred_skills          40     33     73
posting_date              73      0     73
post_until                51     22     73

In [33]:
regex_pattern = r"\b(sql)\b|\b(tableau)\b|\b(powerbi)\b|\b(power bi)\b|\b(phyton)\b|\b(eda)\b|\b(llm)\b|\b(ai)\b|\b(machine learning)\b|\b(ml)\b|\b(pandas)\b|\b(numpy)\b|\b(oracle)\b"
# regex_pattern = r"\b(sql|tableau|bi|phyton|eda|llm|ai|ml|pandas|numpy|oracle)\b"
df_keywords = filter_by_regex_pattern(df_merged,'preferred_skills', regex_pattern)

d:\vscode101\first_project\notebooks\functions.py:54: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask = df[column].str.contains(regex_pattern, flags=re.IGNORECASE, na=False, regex=True)

In [34]:
df_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 213 entries, 0 to 212
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_id             213 non-null    int64
 1   agency             213 non-null    object
 2   #_of_positions     213 non-null    int64
 3   business_title     213 non-null    object
 4   level              213 non-null    object
 5   job_category       213 non-null    object
 6   career_level       213 non-null    object
 7   salary_range_from  213 non-null    float64
 8   salary_range_to    213 non-null    float64
 9   salary_frequency   213 non-null    object
 10  preferred_skills   213 non-null    object
 11  posting_date       213 non-null    datetime64[ns]
 12  post_until         63 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(7)
memory usage: 21.8+ KB

In [35]:
display(pd.DataFrame({
    "non_nulls": df_keywords.count(),
    "nulls": df_keywords.isnull().sum(),
    "total": len(df_keywords)
}))

                   non_nulls  nulls  total
job_id                   213      0    213
agency                   213      0    213
#_of_positions           213      0    213
business_title           213      0    213
level                    213      0    213
job_category             213      0    213
career_level             213      0    213
salary_range_from        213      0    213
salary_range_to          213      0    213
salary_frequency         213      0    213
preferred_skills         213      0    213
posting_date             213      0    213
post_until                63    150    213

In [36]:
# Find intersection of job_ids
common_ids = set(df_data_analyst['job_id']).intersection(set(df_keywords['job_id']))

# Extract rows from either DataFrame with those ids
df_overlap_analyst = df_data_analyst[df_data_analyst['job_id'].isin(common_ids)]
df_overlap_keywords = df_keywords[df_keywords['job_id'].isin(common_ids)]

df_overlap = df_merged[df_merged['job_id'].isin(common_ids)]

# Show all overlapping job_ids
print("Number of overlapping jobs:", len(common_ids))
print("Overlapping job_ids:", common_ids)

# Show the rows
df_overlap.head(10)

Number of overlapping jobs: 25
Overlapping job_ids: {631821, 716689, 631322, 725019, 719131, 638493, 728611, 634790, 708398, 683058, 598334, 598337, 594373, 605517, 633678, 621008, 605529, 629470, 723937, 604898, 605039, 732400, 711157, 732792, 627069}

,job_id,agency,#_of_positions,business_title,level,job_category,career_level,salary_range_from,salary_range_to,salary_frequency,preferred_skills,posting_date,post_until
231,598334,department of transportation,1,senior it business analyst,0,technology data innovation,experienced non,75000.0,160000.0,annual,5 years of experience in business analysis or...,2023-08-27,NaT
473,631821,dept of design construction,1,data science manager,0,engineering architecture planning policy rese...,experienced non,75000.0,128750.0,annual,strong analytical collaborative problem solvin...,2024-04-04,NaT
548,605039,department of investigation,1,associate data analyst,0,communications intergovernmental affairs poli...,experienced non,85000.0,96000.0,annual,masters degree or advanced coursework in comp...,2023-09-15,2024-07-11
573,604898,department of transportation,1,senior data scientist,4a,policy research analysis,experienced non,103026.0,133630.0,annual,this position requires experience working with...,2023-09-20,NaT
740,621008,office of emergency management,1,process and data analyst human capital,1,administration human resources technology dat...,experienced non,65000.0,72500.0,annual,strong communication and writing skills and a...,2024-04-15,2024-05-26
981,594373,nyc housing authority,1,senior business intelligence data analyst,2,technology data innovation,experienced non,93288.0,120190.0,annual,experience developing implementing and mainta...,2023-08-02,NaT
1365,629470,financial info svcs agency,2,business analyst pms,0,technology data innovation,experienced non,75000.0,130000.0,annual,technical as well as business knowledge and e...,2024-03-11,NaT
1569,631322,dept of health hygiene,1,data analyst bureau of environmental sciences ...,1,health policy research analysis,experienced non,70087.0,70087.0,annual,experience with data systems exploratory data...,2024-03-26,2024-07-24
1648,598337,department of transportation,2,it business analyst,0,technology data innovation,experienced non,75000.0,160000.0,annual,3 years of experience in business communicati...,2023-08-21,NaT
2244,605517,department of transportation,1,data scientist,1,technology data innovation policy research a...,experienced non,70087.0,84805.0,annual,ideal candidates must be able to demonstrate s...,2023-09-21,NaT

In [37]:
# Create the exclusion key set
exclude_keys = pd.concat([df_data_analyst[['job_id']], df_keywords[['job_id']]]).drop_duplicates()

# Merge with indicator to track exclusive rows
df_excluded = df_merged.merge(exclude_keys, on=['job_id'], how='left', indicator=True)

# Keep only rows that were NOT matched
df_other = df_excluded[df_excluded['_merge'] == 'left_only'].drop(columns=['_merge'])

df_excluded['_merge'].unique()

['left_only', 'both']
Categories (3, object): ['left_only', 'right_only', 'both']

In [38]:
display(pd.DataFrame({
    "non_nulls": exclude_keys.count(),
    "nulls": exclude_keys.isnull().sum(),
    "total": len(exclude_keys)
}))

        non_nulls  nulls  total
job_id        261      0    261

In [39]:
df_other.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5010 entries, 0 to 5270
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   job_id             5010 non-null   int64
 1   agency             5010 non-null   object
 2   #_of_positions     5010 non-null   int64
 3   business_title     5010 non-null   object
 4   level              5010 non-null   object
 5   job_category       5010 non-null   object
 6   career_level       5010 non-null   object
 7   salary_range_from  5010 non-null   float64
 8   salary_range_to    5010 non-null   float64
 9   salary_frequency   5010 non-null   object
 10  preferred_skills   3110 non-null   object
 11  posting_date       5010 non-null   datetime64[ns]
 12  post_until         1897 non-null   datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(2), object(7)
memory usage: 548.0+ KB

In [40]:
display(pd.DataFrame({
    "non_nulls": df_other.count(),
    "nulls": df_other.isnull().sum(),
    "total": len(df_other)
}))

                   non_nulls  nulls  total
job_id                  5010      0   5010
agency                  5010      0   5010
#_of_positions          5010      0   5010
business_title          5010      0   5010
level                   5010      0   5010
job_category            5010      0   5010
career_level            5010      0   5010
salary_range_from       5010      0   5010
salary_range_to         5010      0   5010
salary_frequency        5010      0   5010
preferred_skills        3110   1900   5010
posting_date            5010      0   5010
post_until              1897   3113   5010

In [41]:
# Audit Explanation:
# Naive sum double-counts overlaps, so it’s larger than the universe (df_merged).
# Subtracting overlap gives the original postings count, confirming your splits are accurate.
# This is normal and expected in set operations where groups overlap.
summary = pd.DataFrame({
    'DataFrame': ['df_merged', 'df_data_analyst', 'df_keywords', 'df_other', 'df_overlap', 'Sum (naive)', 'Sum (minus overlap)'],
    'Count': [len(df_merged), len(df_data_analyst), len(df_keywords), len(df_other), len(df_overlap), 
              len(df_data_analyst) + len(df_keywords) + len(df_other), 
              len(df_data_analyst) + len(df_keywords) + len(df_other) - len(df_overlap)],
    'Description': [
        'All unique job postings',
        'Data Analyst/Engineer job postings',
        'Mentions data skills in preferred_skills',
        'Remaining postings (not analyst/keywords)',
        'Postings in both analyst and keywords',
        'Naive sum (overlap double-counted)', 
        'Corrected sum (overlap subtracted)'
    ]
})

display(summary)

             DataFrame  Count                                Description
0            df_merged   5271                    All unique job postings
1      df_data_analyst     73         Data Analyst/Engineer job postings
2          df_keywords    213   Mentions data skills in preferred_skills
3             df_other   5010  Remaining postings (not analyst/keywords)
4           df_overlap     25      Postings in both analyst and keywords
5          Sum (naive)   5296         Naive sum (overlap double-counted)
6  Sum (minus overlap)   5271         Corrected sum (overlap subtracted)

In [42]:
df_other.to_csv(config['output_data']['file1'], index=False, sep=",", encoding="utf-8")
df_data_analyst.to_csv(config['output_data']['file2'], index=False, sep=",", encoding="utf-8")
df_keywords.to_csv(config['output_data']['file3'], index=False, sep=",", encoding="utf-8")
df_overlap.to_csv(config['output_data']['file4'], index=False, sep=",", encoding="utf-8")